import React from "react";
import type { Metadata } from 'next'
import './globals.css'
import Header from "@/app/LayoutComponents/Header/Header";
import {Roboto} from "next/font/google"

// Шрифт
const roboto = Roboto({
    subsets: ["cyrillic-ext"],
    weight: ['300', '400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Cian App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
